### ISSUE TITLE
Возможность включать и отключать видео

### ISSUE THREAD

**Issue by gozaltech** [beqabeqa473/YoutubePlayer#128]
Reported by Вадим
А возможно ли сделать так, чтобы можно было бы вручную включать и отключать видео? Например, если человек в семье зрячий, то мог бы включать для себя видео, либо человек с подглядом...

**Comment by beqabeqa473** [comment]
видео принципиально нет. смотрите в браузере

On 2/16/19, gozaltech <notifications@github.com> wrote:
> Reported by Вадим
> А возможно ли сделать так, чтобы можно было бы вручную включать и отключать
> видео? Например, если человек в семье зрячий, то мог бы включать для себя
> видео, либо человек с подглядом...
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/beqabeqa473/YoutubePlayer/issues/128


-- 
with best regards beqa
