### ISSUE TITLE
Контекстное меню в результатах поиска

### ISSUE THREAD

**Issue by gozaltech** [beqabeqa473/YoutubePlayer#95]
Reported by Вадим
Спасибо вам за программу! Если можно, ещё было бы удобно, если бы в контекстном меню результатов поиска был пункт "Скопировать ссылку", чтобы можно было отправить скопированную ссылку другому человеку, например.

**Comment by beqabeqa473** [comment]
будет копирование ссылки а также скачивание

On 2/14/19, gozaltech <notifications@github.com> wrote:
> Reported by Вадим
> Спасибо вам за программу! Если можно, ещё было бы удобно, если бы в
> контекстном меню результатов поиска был пункт "Скопировать ссылку", чтобы
> можно было отправить скопированную ссылку другому человеку, например.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/beqabeqa473/YoutubePlayer/issues/95


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
готово
